using System.Text.Json.Serialization;

namespace ASPAssistant.Core.Models;

/// <summary>
/// A Garrison Protocol boss entry loaded from the local <c>bosses.json</c>
/// (generated by <c>fetch_spdatabase.py</c>).
/// </summary>
public class BossInfo
{
    [JsonPropertyName("enemyId")]
    public string EnemyId { get; set; } = "";

    [JsonPropertyName("enemyIndex")]
    public string EnemyIndex { get; set; } = "";

    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    /// <summary>
    /// Optional extra lookup keys (e.g. short UI text) so OCR can match without the full name.
    /// </summary>
    [JsonPropertyName("aliases")]
    public List<string> Aliases { get; set; } = [];

    [JsonPropertyName("description")]
    public string? Description { get; set; }

    [JsonPropertyName("attackType")]
    public string? AttackType { get; set; }

    [JsonPropertyName("damageTypes")]
    public List<string> DamageTypes { get; set; } = [];

    [JsonPropertyName("abilityList")]
    public List<string> AbilityList { get; set; } = [];

    /// <summary>
    /// Path relative to <c>data/</c> — e.g. <c>icons/bosses/enemy_9006_actoxi.png</c>.
    /// Combine with <c>AppContext.BaseDirectory + "data"</c> at load time.
    /// </summary>
    [JsonPropertyName("iconPath")]
    public string IconPath { get; set; } = "";
}
