using System.Text.Json.Serialization;

namespace ASPAssistant.Core.Models;

/// <summary>
/// One special-enemy variant (a "representative" enemy that can be selected
/// for a given type within one game session).
/// </summary>
public class EnemyVariant
{
    [JsonPropertyName("specialEnemyId")]
    public string SpecialEnemyId { get; set; } = "";

    /// <summary>
    /// Display name for tooltip text. Falls back to <see cref="SpecialEnemyId"/>
    /// when upstream data has no localized enemy name.
    /// </summary>
    [JsonPropertyName("enemyName")]
    public string EnemyName { get; set; } = "";

    /// <summary>
    /// Relative path under <c>data/</c>, e.g. <c>icons/enemies/enemy_1041_lazerd.png</c>.
    /// </summary>
    [JsonPropertyName("iconPath")]
    public string IconPath { get; set; } = "";

    [JsonPropertyName("weight")]
    public int Weight { get; set; }

    [JsonIgnore]
    public string TooltipName =>
        string.IsNullOrWhiteSpace(EnemyName) ? SpecialEnemyId : EnemyName;
}

/// <summary>
/// Data for one special-enemy type (飞行 / 频次 / 元素 / 持续 / 隐匿 / 折射 / 特异).
/// Loaded from the local <c>enemy_types.json</c> generated by <c>fetch_spdatabase.py</c>.
/// </summary>
public class EnemyTypeEntry
{
    [JsonPropertyName("typeCode")]
    public string TypeCode { get; set; } = "";

    /// <summary>Chinese name matching the OCR suffix, e.g. "飞行".</summary>
    [JsonPropertyName("typeName")]
    public string TypeName { get; set; } = "";

    /// <summary>
    /// Relative path to the type icon under <c>data/</c>,
    /// e.g. <c>icons/enemy_types/FLY.png</c>.
    /// </summary>
    [JsonPropertyName("typeIconPath")]
    public string TypeIconPath { get; set; } = "";

    /// <summary>Variants that appear in the first half of the game (前半段).</summary>
    [JsonPropertyName("firstHalfVariants")]
    public List<EnemyVariant> FirstHalfVariants { get; set; } = [];

    /// <summary>Variants that appear in the second half of the game (后半段).</summary>
    [JsonPropertyName("secondHalfVariants")]
    public List<EnemyVariant> SecondHalfVariants { get; set; } = [];
}
